apiVersion: v1
kind: ReplicationController
metadata:
  name: legacy-mariadb-example
spec:
  replicas: 1 
  selector:
    name: legacy-mariadb-example
  template:
    metadata:
      name: legacy-mariadb-example
      labels:
        name: legacy-mariadb-example
      annotations:
        pod.network.openshift.io/assign-macvlan: "true"
    spec:
      containers:
      - name: egress-router-mariadb
        image: registry.access.redhat.com/openshift3/ose-egress-router
        env:
        - name: EGRESS_SOURCE
          value: 171.1.1.100
        - name: EGRESS_GATEWAY
          value: 172.1.1.1
        - name: EGRESS_DESTINATION
          value: 172.16.0.5
        securityContext:
          privileged: true
